### ISSUE TITLE
termcolor overwrites initial windows console colors

### ISSUE THREAD

**Issue by rivy** [BurntSushi/termcolor#4] opened 2018-08-06 01:22 UTC
When using "termcolor" with Windows 10 (ANSI capable), initial text color/intensity attributes are not preserved. This can cause color shifting when the console doesn't start in the "default" color mode, either by using `color xx` or another application which has recolored the console.

Notably, "wincolor" does save the initial text attributes and restores them with `reset()`.

But "termcolor", at least when using ANSI output, doesn't correctly restore the initial text attributes colors/intensities.

I initially discovered the bug in `cargo`, then traced it to "termcolor".

``` shell
C:\#temp\repo> ver
Microsoft Windows [Version 10.0.16299.492]
C:\#temp\repo> rustc --version
rustc 1.30.0-nightly (3edb355b7 2018-08-03)
```

Examples...

``` rust
// wincolor example
// * has correct output
extern crate wincolor;

use wincolor::{Color, Console, Intense};

fn main() {
    let mut con = Console::stdout().expect("open console failed");
    println!("normal text");
    con.fg(Intense::Yes, Color::Cyan).expect("set fg failed");
    println!(" ... intense cyan text");
    con.reset().expect("reset failed");
    println!(" ... normal text");
}
```
![image](https://user-images.githubusercontent.com/80132/43692239-abb063c2-98eb-11e8-85db-ea028c3f6205.png)

``` rust
// termcolor example
// * broken output
extern crate termcolor;

use std::io::Write;
use termcolor::{Color, ColorChoice, ColorSpec, StandardStream, WriteColor};

fn main() {
    let mut stdout = StandardStream::stdout(ColorChoice::Always);
    writeln!(&mut stdout, "normal text");
    stdout.set_color(ColorSpec::new().set_intense(true).set_fg(Some(Color::Cyan))).expect("set_color failed");
    writeln!(&mut stdout, " ... intense cyan text");
    stdout.reset().expect("reset failed");
    writeln!(&mut stdout, " ... normal text");
}
```
![image](https://user-images.githubusercontent.com/80132/43692293-384d3756-98ec-11e8-8156-45231e65a0f5.png)

I'm happy to help test solutions. But my rust-fu is poor at the moment as I've only just started playing with the language.

Thanks for the attention.

**Comment by BurntSushi** [comment] 2018-08-06 10:57
Thanks for reporting this! I can't debug this at the moment, but I'll check it out when I get chance.

Just riffing on this a bit in case you want to debug this, I'm not really sure what's going on. In particular, when using ANSI escapes, `reset` will [emit the standard "reset" sequence](https://github.com/BurntSushi/termcolor/blob/e6319861881fda18855d8d17d0a35c87a0339232/src/lib.rs#L1120-L1122), which is indeed compatible with [Windows 10 documented support for console virtual terminal sequences](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#span-idtextformattingspanspan-idtextformattingspanspan-idtextformattingspantext-formatting). There's really nothing else to it here, and if it were broken, I'd also expect ripgrep's colors (for example) to be badly broken too, but I don't think I've seen that problem.

One interesting thing in your example is that the "cyan" color text is reset.

To make sure I'm being clear here, there should be no reason to "record" the current styling like `wincolor` does when it uses the console APIs, because the console APIs don't have a "reset" sequence like the ANSI escapes.

**Comment by rivy** [comment] 2018-08-06 20:15
`ripgrep` (and `cargo`, for that matter) also has the same issue.

![image](https://user-images.githubusercontent.com/80132/43737770-09f2f192-9988-11e8-8706-7f3c928b0659.png)

Ultimately, I think its likely a Windows console bug. In fumbling around with it. I've noticed that if ...

1. if the console color is changed (eg, `color 40`) and then
2. the "Properties" dialog of the console window is opened, and then 
3. confirmed with "OK", 

the problem disappears.

![image](https://user-images.githubusercontent.com/80132/43737795-256495ca-9988-11e8-8db8-9604e97f14ad.png)

A simple work-around might be to just add an option to force console API use, even when the Windows version supports ANSI.

Alternatively, a wincolor function could be implemented that returns the initial character attributes. Those initial attributes could be used in various ways to preserve the user's baseline color choice (either in a customizable reset() function, resetting to specific attribute set at end-of-line, or to push that specific attribute set out as a manual reset before exiting the application). But, that's likely a big logical mess-in-the-making.

**Comment by BurntSushi** [comment] 2018-08-06 22:41
@rivy Thanks for the extra debugging! I had a chance to play around with this today and unfortunately couldn't reproduce it. i.e., ripgrep's colors appear to be working just fine.

If this is a bug in the Windows console, I'd support an override that prevents ANSI escapes from being used. Seems unfortunate, but alas.

I definitely do not want to get in the business of saving and restoring color settings when it comes to ANSI escapes. The set of possible styles is too large. I did it for the console because the styling is very limited and because, well, you kind of have to.

**Comment by BurntSushi** [comment] 2018-08-22 13:00
I'm going to close this at `wontfix` under the assumption that there is a Windows console bug lurking here. If more data comes to light we can re-open. I'd also be willing to accept a _small_ patch that forces a work-around here, if that helps.

**Closed as completed by BurntSushi** 2018-08-22 13:00 UTC
Labels: wontfix
